name: docker-buildx

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Docker Login
        if: success() && github.event_name != 'pull_request'
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Publish the proxy docker image
      - name: Docker Buildx (build and push) - Proxy
        if: success() && github.event_name != 'pull_request'
        run: |
          docker buildx create --use --name build --node build
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6 \
            --push \
            --tag swarpf/proxy:latest \
            --file ./Dockerfile ./

      - name: Docker Check Manifest
        if: always() && github.event_name != 'pull_request'
        run: |
          docker run --rm mplatform/mquery swarpf/proxy:latest

